/*
 * bios.asm.js — the VOLTA-16 firmware, as source.
 *
 * These 3.5k words of assembly are assembled by the assembler in volta.js at
 * boot and burned into the top of every machine's address space. Every
 * cartridge calls into this ROM. The font and sine table are generated by
 * the tools in tools/ (see js/font.inc.js and js/sine.inc.js).
 */

import { FONT_ASM } from './font.inc.js';
import { SINE_ASM } from './sine.inc.js';

const BIOS_CODE = `
; ═══════════════════════════════════════════════════════════════════════════
;  VOLTA-16 SYSTEM ROM  ·  12.288 MHz  ·  (c) 1983 VOLTA COMPUTER COMPANY
;
;  Calling convention. Arguments travel in R0–R4. Every subroutine saves
;  and restores R0–R7, so a cartridge may call the BIOS at any time without
;  worrying about its own registers. Results, where documented, arrive in R0.
;
;     0xF000  BIOS_CLR    R0 = colour                  fill the screen
;     0xF002  BIOS_PIXEL  R0 = x, R1 = y, R2 = colour  plot one pixel
;     0xF004  BIOS_RECT   R0 = x, R1 = y, R2 = w, R3 = h, R4 = colour
;     0xF006  BIOS_HLINE  R0 = x, R1 = y, R2 = len, R3 = colour
;     0xF008  BIOS_CHAR   R0 = char, R1 = x, R2 = y, R3 = colour
;     0xF00A  BIOS_PRINT  R0 = string, R1 = x, R2 = y, R3 = colour
;     0xF00C  BIOS_NUM    R0 = value, R1 = x, R2 = y, R3 = colour
;     0xF00E  BIOS_SIN    R0 = angle (0–255)  ->  R0 = sin * 256 (signed)
;     0xF010  BIOS_COS    R0 = angle (0–255)  ->  R0 = cos * 256 (signed)
;     0xF012  BIOS_CHAR2  R0 = char, R1 = x, R2 = y, R3 = colour  (2x scale)
;
;  The glyph table lives at 0xF200 (64 glyphs × 7 rows, 5 bits wide) and the
;  sine table at 0xF600 (256 signed values, amplitude 256). Scratch space
;  for the number printer is at 0xF7F0.
; ═══════════════════════════════════════════════════════════════════════════

.org 0xF000
    JMP clr
    JMP pixel
    JMP rect
    JMP hline
    JMP char
    JMP print
    JMP num
    JMP sin
    JMP cos
    JMP char2

; ── CLR ────────────────────────────────────────────────────────────────────
; Fill the entire frame buffer with the colour in R0. The DMA fill engine
; does the heavy lifting, so this returns in a dozen cycles.
clr:
    PUSH R1
    LDI R1, VRAM
    STA FILL_COLOR, R0
    LDI R0, VRAM_W*VRAM_H
    STA FILL_LEN, R0
    STA FILL_START, R1
    POP R1
    RET

; ── PIXEL ──────────────────────────────────────────────────────────────────
; Plot one pixel, clipped to the visible 160×120 field.
pixel:
    PUSH R3
    PUSH R4
    LDI R3, VRAM_W
    CMP R0, R3
    JAE pixel_out
    LDI R3, VRAM_H
    CMP R1, R3
    JAE pixel_out
    LDI R3, VRAM_W
    MOV R4, R1
    MUL R4, R3
    ADD R4, R0
    LDI R3, VRAM
    ADD R4, R3
    ST [R4], R2
pixel_out:
    POP R4
    POP R3
    RET

; ── HLINE ──────────────────────────────────────────────────────────────────
; Horizontal line, clipped at both ends, drawn by the fill engine.
hline:
    PUSH R0
    PUSH R1
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LDI R4, VRAM_W
    CMP R0, R4
    JAE hline_out
    LDI R4, VRAM_H
    CMP R1, R4
    JAE hline_out
    CMPI R2, 0
    JE hline_out
    LDI R4, VRAM_W
    CMP R2, R4
    JAE hline_doclip
    MOV R5, R0
    ADD R5, R2
    CMP R5, R4
    JB hline_noclip
hline_doclip:
    SUB R4, R0
    MOV R2, R4
hline_noclip:
    LDI R4, VRAM_W
    MOV R5, R1
    MUL R5, R4
    ADD R5, R0
    LDI R4, VRAM
    ADD R5, R4
    STA FILL_COLOR, R3
    STA FILL_LEN, R2
    STA FILL_START, R5
hline_out:
    POP R5
    POP R4
    POP R3
    POP R2
    POP R1
    POP R0
    RET

; ── RECT ───────────────────────────────────────────────────────────────────
; Filled rectangle, clipped vertically here and horizontally by HLINE.
rect:
    PUSH R1
    PUSH R3
    PUSH R5
    PUSH R6
    LDI R5, VRAM_H
    CMP R1, R5
    JAE rect_done
    SUB R5, R1
    CMP R3, R5
    JB rect_size_ok
    MOV R3, R5
rect_size_ok:
    MOV R5, R3
    MOV R6, R1
rect_loop:
    CMPI R5, 0
    JE rect_done
    MOV R1, R6
    MOV R3, R4
    CALL hline
    INC R6
    DEC R5
    JMP rect_loop
rect_done:
    POP R6
    POP R5
    POP R3
    POP R1
    RET

; ── CHAR ───────────────────────────────────────────────────────────────────
; Draw one glyph from the ROM font. Characters outside 32–95 are ignored.
; The glyph is transparent: only lit pixels are written.
char:
    PUSH R0
    PUSH R1
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    PUSH R6
    PUSH R7
    LDI R4, 32
    CMP R0, R4
    JB char_done
    LDI R4, 96
    CMP R0, R4
    JAE char_done
    LDI R4, VRAM_H
    CMP R2, R4
    JAE char_done
    LDI R4, VRAM_W
    CMP R1, R4
    JAE char_done
    LDI R4, 32
    SUB R0, R4              ; R0 = glyph index 0–63
    MOV R5, R0
    SHLI R5, 3
    SUB R5, R0              ; * 7
    LDI R4, BIOS_FONT
    ADD R5, R4              ; R5 = glyph pointer
    LDI R4, VRAM_W
    MOV R6, R2
    MUL R6, R4
    ADD R6, R1
    LDI R4, VRAM
    ADD R6, R4              ; R6 = first row address
    MOV R0, R2
    LDI R4, VRAM_H
    SUB R4, R0
    LDI R0, 7
    CMP R4, R0
    JB char_rows_ok
    MOV R4, R0
char_rows_ok:
    MOV R2, R4              ; R2 = rows to draw (glyphs are 7 tall)
    MOV R0, R1
    LDI R4, VRAM_W
    SUB R4, R0
    MOV R1, R4              ; R1 = columns available
    MOV R4, R5              ; R4 = glyph pointer
    MOV R5, R6              ; R5 = row address
    LDI R6, 0               ; R6 = row counter
char_row:
    CMP R6, R2
    JAE char_done
    LD R7, [R4]
    INC R4
    CMPI R1, 1
    JB char_next
    LDI R0, 16
    AND R0, R7
    JE char_c1
    ST [R5], R3
char_c1:
    CMPI R1, 2
    JB char_next
    LDI R0, 8
    AND R0, R7
    JE char_c2
    STO [R5+1], R3
char_c2:
    CMPI R1, 3
    JB char_next
    LDI R0, 4
    AND R0, R7
    JE char_c3
    STO [R5+2], R3
char_c3:
    CMPI R1, 4
    JB char_next
    LDI R0, 2
    AND R0, R7
    JE char_c4
    STO [R5+3], R3
char_c4:
    CMPI R1, 5
    JB char_next
    LDI R0, 1
    AND R0, R7
    JE char_next
    STO [R5+4], R3
char_next:
    LDI R0, VRAM_W
    ADD R5, R0
    INC R6
    JMP char_row
char_done:
    POP R7
    POP R6
    POP R5
    POP R4
    POP R3
    POP R2
    POP R1
    POP R0
    RET

; ── CHAR2 ──────────────────────────────────────────────────────────────────
; The same glyph at double size, for title screens and splash pages.
; Each lit font pixel becomes a 2x2 block; the character cell is 12 px wide.
char2:
    PUSH R0
    PUSH R1
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    PUSH R6
    PUSH R7
    LDI R4, 32
    CMP R0, R4
    JB char2_done
    LDI R4, 96
    CMP R0, R4
    JAE char2_done
    LDI R4, VRAM_H
    CMP R2, R4
    JAE char2_done
    LDI R4, VRAM_W
    CMP R1, R4
    JAE char2_done
    LDI R4, 32
    SUB R0, R4
    MOV R5, R0
    SHLI R5, 3
    SUB R5, R0
    LDI R4, BIOS_FONT
    ADD R5, R4
    LDI R4, VRAM_W
    MOV R6, R2
    MUL R6, R4
    ADD R6, R1
    LDI R4, VRAM
    ADD R6, R4
    MOV R0, R2
    LDI R4, VRAM_H
    SUB R4, R0
    SHRI R4, 1
    LDI R0, 7
    CMP R4, R0
    JB char2_rows_ok
    MOV R4, R0
char2_rows_ok:
    MOV R2, R4
    MOV R0, R1
    LDI R4, VRAM_W
    SUB R4, R0
    SHRI R4, 1
    MOV R1, R4
    MOV R4, R5
    MOV R5, R6
    LDI R6, 0
char2_row:
    CMP R6, R2
    JAE char2_done
    LD R7, [R4]
    INC R4
    CMPI R1, 1
    JB char2_next
    LDI R0, 16
    AND R0, R7
    JE char2_c1
    ST [R5], R3
    STO [R5+1], R3
    STO [R5+160], R3
    STO [R5+161], R3
char2_c1:
    CMPI R1, 2
    JB char2_next
    LDI R0, 8
    AND R0, R7
    JE char2_c2
    STO [R5+2], R3
    STO [R5+3], R3
    STO [R5+162], R3
    STO [R5+163], R3
char2_c2:
    CMPI R1, 3
    JB char2_next
    LDI R0, 4
    AND R0, R7
    JE char2_c3
    STO [R5+4], R3
    STO [R5+5], R3
    STO [R5+164], R3
    STO [R5+165], R3
char2_c3:
    CMPI R1, 4
    JB char2_next
    LDI R0, 2
    AND R0, R7
    JE char2_c4
    STO [R5+6], R3
    STO [R5+7], R3
    STO [R5+166], R3
    STO [R5+167], R3
char2_c4:
    CMPI R1, 5
    JB char2_next
    LDI R0, 1
    AND R0, R7
    JE char2_next
    STO [R5+8], R3
    STO [R5+9], R3
    STO [R5+168], R3
    STO [R5+169], R3
char2_next:
    LDI R0, 320
    ADD R5, R0
    INC R6
    JMP char2_row
char2_done:
    POP R7
    POP R6
    POP R5
    POP R4
    POP R3
    POP R2
    POP R1
    POP R0
    RET

; ── PRINT ──────────────────────────────────────────────────────────────────
; Print a zero-terminated string. x advances six pixels per character.
print:
    PUSH R6
    PUSH R7
    MOV R6, R0
    MOV R7, R1
print_loop:
    LD R0, [R6]
    CMPI R0, 0
    JE print_done
    MOV R1, R7
    CALL char
    INC R6
    ADDI R7, 6
    JMP print_loop
print_done:
    POP R7
    POP R6
    RET

; ── NUM ───────────────────────────────────────────────────────────────────
; Print an unsigned 16-bit number in decimal, no leading zeros.
num:
    PUSH R0
    PUSH R1
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    PUSH R6
    PUSH R7
    MOV R4, R0
    LDI R5, BIOS_SCRATCH
    ADDI R5, 5
    LDI R0, 0
    STO [R5+1], R0          ; terminator
    CMPI R4, 0
    JNE num_loop
    LDI R0, 48
    ST [R5], R0             ; the number zero
    JMP num_emit
num_loop:
    CMPI R4, 0
    JE num_emit_inc
    LDI R6, 10
    MOV R0, R4
    MOD R0, R6
    LDI R7, 48
    ADD R0, R7
    ST [R5], R0
    DEC R5
    DIV R4, R6
    JMP num_loop
num_emit_inc:
    INC R5
num_emit:
    MOV R0, R5
    CALL print
    POP R7
    POP R6
    POP R5
    POP R4
    POP R3
    POP R2
    POP R1
    POP R0
    RET

; ── SIN ────────────────────────────────────────────────────────────────────
; R0 = angle (wraps every 256) -> R0 = sin(angle) * 256, signed.
sin:
    PUSH R1
    LDI R1, 0xFF
    AND R0, R1
    LDI R1, BIOS_SINTAB
    ADD R0, R1
    LD R0, [R0]
    POP R1
    RET

; ── COS ────────────────────────────────────────────────────────────────────
; Cosine is sine a quarter turn early.
cos:
    PUSH R1
    LDI R1, 64
    ADD R0, R1
    CALL sin
    POP R1
    RET
`;

export const BIOS_ASM = `${BIOS_CODE}
.org 0xF300
${FONT_ASM}
.org 0xF600
${SINE_ASM}
`;
