/*
 * gennotes.mjs — note periods for the VOLTA-16 sound chip.
 *
 * Pulse frequency = 12288 / (period + 1) Hz, so period = round(12288/f) - 1.
 * Emits JS constants N_<note><octave> used as assembler symbols by the
 * cartridge build. Regenerate with:
 *
 *   node tools/gennotes.mjs
 */

import { writeFileSync } from 'node:fs';

const NAMES = ['C', 'CS', 'D', 'DS', 'E', 'F', 'FS', 'G', 'GS', 'A', 'AS', 'B'];
const entries = [];
for (let octave = 1; octave <= 6; octave++) {
  for (let i = 0; i < 12; i++) {
    const midi = (octave + 1) * 12 + i;
    const freq = 440 * 2 ** ((midi - 69) / 12);
    const period = Math.max(0, Math.min(65535, Math.round(12288 / freq) - 1));
    entries.push([`N_${NAMES[i]}${octave}`, period]);
  }
}
const lines = [];
lines.push('/* Generated by tools/gennotes.mjs — do not edit by hand. */');
lines.push('export const NOTES = {');
for (const [name, period] of entries) lines.push(`  ${name}: ${period},`);
lines.push('};');
writeFileSync(new URL('../js/notes.inc.js', import.meta.url), lines.join('\n') + '\n');
console.log(`wrote js/notes.inc.js (${entries.length} notes)`);
