/*
 * gensine.mjs — the BIOS sine table.
 *
 * 256 entries, one per angle step (0–255 = 0–360°), value = sin * 256 as a
 * signed 16-bit word. Writes js/sine.inc.js. Regenerate with:
 *
 *   node tools/gensine.mjs
 */

import { writeFileSync } from 'node:fs';

const rows = [];
for (let i = 0; i < 256; i++) {
  const v = Math.round(Math.sin((i / 256) * Math.PI * 2) * 256) & 0xffff;
  rows.push(`0x${v.toString(16).padStart(4, '0')}`);
}
const lines = [];
lines.push('; ── SINTAB ── 256 signed sine values, amplitude 256, angle = index ──');
for (let i = 0; i < 256; i += 8) {
  lines.push(`    .word ${rows.slice(i, i + 8).join(', ')}`);
}
const body = lines.join('\n');
const out = `/* Generated by tools/gensine.mjs — do not edit by hand. */
export const SINE_ASM = ${JSON.stringify(body)};
`;
writeFileSync(new URL('../js/sine.inc.js', import.meta.url), out);
console.log('wrote js/sine.inc.js (256 values)');
