/*
 * gensong.mjs — the cartridge theme, as data.
 *
 * A 64-row loop in A minor: arpeggio lead, octave-jumping bass and a noise
 * drum kit. Rows are written as note names; the tool emits `.word` lines of
 * assembler symbols so the track reads like a score in the source viewer.
 *
 *   node tools/gensong.mjs
 */

import { writeFileSync } from 'node:fs';

const B = (bar) => bar.flat();
const rest = (n) => Array(n).fill('0');

const lead = B([
  ['E5', 0, 'C5', 0, 'A4', 0, 'C5', 0, 'E5', 0, 'A5', 0, 'G5', 0, 'E5', 0],
  ['F5', 0, 'C5', 0, 'A4', 0, 'C5', 0, 'F5', 0, 'A5', 0, 'G5', 0, 'F5', 0],
  ['E5', 0, 'C5', 0, 'G4', 0, 'C5', 0, 'E5', 0, 'G5', 0, 'E5', 0, 'C5', 0],
  ['D5', 0, 'B4', 0, 'G4', 0, 'B4', 0, 'D5', 0, 'G5', 0, 'FS5', 0, 'D5', 0],
]);

const bass = B([
  ['A2', 0, 0, 0, 'A3', 0, 0, 0, 'A2', 0, 0, 0, 'E3', 0, 0, 0],
  ['F2', 0, 0, 0, 'F3', 0, 0, 0, 'F2', 0, 0, 0, 'C3', 0, 0, 0],
  ['C3', 0, 0, 0, 'C4', 0, 0, 0, 'C3', 0, 0, 0, 'G3', 0, 0, 0],
  ['G2', 0, 0, 0, 'G3', 0, 0, 0, 'G2', 0, 0, 0, 'D3', 0, 0, 0],
]);

const drumBar = ['K', 0, 'H', 0, 'S', 0, 'H', 0, 'K', 0, 'H', 0, 'S', 0, 'H', 0];
const drum = B([[...drumBar], [...drumBar], [...drumBar], [...drumBar]]);

const DRUMS = { K: 'D_KICK', S: 'D_SNARE', H: 'D_HAT' };
const symbol = (row, i) => {
  const v = row[i];
  if (v === 0 || v === '0') return '0';
  if (DRUMS[v]) return DRUMS[v];
  return `N_${v}`;
};

const names = { lead: 'song_lead', bass: 'song_bass', drum: 'song_drum' };
const blocks = [];
for (const [key, rows] of [['lead', lead], ['bass', bass], ['drum', drum]]) {
  const lines = [`${names[key]}:`];
  for (let i = 0; i < 64; i += 8) {
    const cells = [];
    for (let j = i; j < i + 8; j++) cells.push(symbol(rows, j));
    lines.push(`    .word ${cells.join(', ')}  ; row ${String(i).padStart(2, '0')}`);
  }
  blocks.push(lines.join('\n'));
}

const out = `/* Generated by tools/gensong.mjs — do not edit by hand. */
export const SONG_ASM = ${JSON.stringify(blocks.join('\n\n'))};
`;
writeFileSync(new URL('../js/song.inc.js', import.meta.url), out);
console.log('wrote js/song.inc.js (64 rows x 3 channels)');
